### ISSUE TITLE
Deploy to staging

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1052]
do itttt

- [ ] all github issues in "deployed to QA" column have been reviewed

Post here if things get... fiddly

**Comment by compwron** [comment]
casa-r4g-staging
f92b5d51

zrivkap@gmail.com
Deployed Sep 22 at 6:25 PM
 Release v350 failed • Retry 
…
bundle exec rake db:migrate && bundle exec rake after_party:run exited with an error.
<img width="455" alt="Screen Shot 2020-10-12 at 11 01 57 PM" src="https://user-images.githubusercontent.com/578159/95821563-00777080-0cdf-11eb-88ea-6be5fa39fed3.png">


https://dashboard.heroku.com/apps/casa-r4g-staging/activity/releases/a9a908ba-7f09-4e9c-b385-a30ee4797bb3

```
D, [2020-10-13T06:01:00.088603 #34] DEBUG -- :   CaseContactContactType Load (2.1ms)  SELECT "case_contact_contact_types".* FROM "case_contact_contact_types" WHERE "case_contact_contact_types"."case_contact_id" = $1 AND "case_contact_contact_types"."contact_type_id" IS NULL LIMIT $2  [["case_contact_id", 1901], ["LIMIT", 1]]
I, [2020-10-13T06:01:01.431940 #34]  INFO -- [Bugsnag]: Notifying https://notify.bugsnag.com of ActiveRecord::RecordInvalid
I, [2020-10-13T06:01:01.477986 #34]  INFO -- [Bugsnag]: Notifying https://notify.bugsnag.com of ActiveRecord::RecordInvalid
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Contact type must exist
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:80:in `raise_validation_error'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:53:in `save!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:318:in `block in save!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:212:in `transaction'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:318:in `save!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/suppressor.rb:48:in `save!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:55:in `create!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:115:in `block in create!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:407:in `block in scoping'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:784:in `_scoping'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:407:in `scoping'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:115:in `create!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:176:in `find_or_create_by!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/querying.rb:21:in `find_or_create_by!'
/app/lib/tasks/deployment/20201005203405_populate_case_contact_contact_type.rake:25:in `block (4 levels) in <main>'
/app/lib/tasks/deployment/20201005203405_populate_case_contact_contact_type.rake:24:in `each'
/app/lib/tasks/deployment/20201005203405_populate_case_contact_contact_type.rake:24:in `block (3 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:70:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:70:in `block in find_each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:222:in `loop'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:222:in `in_batches'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:69:in `find_each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/querying.rb:21:in `find_each'
/app/lib/tasks/deployment/20201005203405_populate_case_contact_contact_type.rake:23:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.17.0/lib/bugsnag/integrations/rake.rb:20:in `execute'
/app/vendor/bundle/ruby/2.7.0/gems/after_party-1.11.2/lib/tasks/deploy_task_runner.rake:6:in `block (3 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/after_party-1.11.2/lib/tasks/deploy_task_runner.rake:6:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/after_party-1.11.2/lib/tasks/deploy_task_runner.rake:6:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.17.0/lib/bugsnag/integrations/rake.rb:20:in `execute'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/app/bin/bundle:133:in `load'
/app/bin/bundle:133:in `<main>'
Tasks: TOP => after_party:populate_case_contact_contact_type
(See full trace by running task with --trace)
```

**Comment by compwron** [comment]
ran `bundle exec rake db:migrate` in `heroku run bash --app casa-qa` Success

**Comment by compwron** [comment]
ran `bundle exec rake after_party:run` in `heroku run bash --app casa-qa` expecting an error, got "no pending tasks to run" 

ahh the new code is not there yet, maybe re-run the heroku connect? 
nope

**Comment by compwron** [comment]
Aha the problem is that there are CaseContacts with nil contact type in the db
How did those get there
`CaseContact.all.map(&:contact_types).select {|ct| ct.nil?}.count # 10`

**Comment by compwron** [comment]
`CaseContact.all.select {|cc| cc.contact_types.nil?}.map(&:id)` 
`[929, 931, 923, 926, 932, 933, 934, 935, 936, 937]`

**Comment by compwron** [comment]
`DISABLE_DATABASE_ENVIRONMENT_CHECK=1 rake db:seed:replant` in qa
this may not be the best idea (because we can't do it in prod and this is supposed to be practice for prod) but it's QA so why not 
![Screen Shot 2020-10-12 at 11 15 15 PM](https://user-images.githubusercontent.com/578159/95822471-d45cef00-0ce0-11eb-90d1-7cd52b722fec.png)


uh so I've been in heroku QA console instead of heroku staging console, my bad
ugh

**Comment by compwron** [comment]
TODO rename staging from casa-r4g-staging to casa-staging

`heroku run bash --app casa-r4g-staging`
`heroku run rails c --app casa-r4g-staging`

**Comment by compwron** [comment]
https://github.com/rubyforgood/casa/issues/1056

**Comment by compwron** [comment]
https://github.com/rubyforgood/casa/commit/fa55197f9138e56d2d285fd46200bef4bee2e73f
Sorry about the autoformat whoops

**Comment by compwron** [comment]
argh https://travis-ci.org/github/rubyforgood/casa/builds/735272408

**Comment by compwron** [comment]
https://github.com/rubyforgood/casa/commit/e70258b69e9420fd91921aeaede916b364c26501
I promise I'm a better sre when I'm awake and getting paid

**Comment by compwron** [comment]
https://travis-ci.com/github/rubyforgood/casa/builds/189640072
https://github.com/rubyforgood/casa/commit/6c97bd8eb225aec9d1b170f5cef9cd6ea2fd829d

dear my future self, in case it isn't blindingly obvious, don't merge unrelated PRs while debugging a deploy

**Comment by compwron** [comment]
ok, qa finally deployed, trying staging deploy again
on a related note- Once the staging deploy is done, I want to investigate the possibility of putting the prod code on staging (and running that code's version of seed, then re-doing the deploy from qa to staging- I want to feel more sure that the prod deploy will run smoothly.

**Comment by compwron** [comment]
useful command for debugging `rake after_party:status`

**Comment by compwron** [comment]
nope https://dashboard.heroku.com/apps/casa-r4g-staging/activity/releases/1fb3b162-579c-4a2a-8304-a3210e353c83

pushed a commit which comments afterparty out of Procfile because it's frustrating to debug rake tasks when the code for the task isn't on the server because the task failed

**Comment by compwron** [comment]
y'all i am not winning 
![Uploading Screen Shot 2020-10-13 at 12.19.45 AM.png…]()

**Comment by compwron** [comment]
Ok I just tried to promote qa to staging (expecting an error) build is at https://dashboard.heroku.com/apps/casa-r4g-staging/activity/releases/1121e872-3087-4e02-9299-fa07701c647a

Since the code that after_party is using has gotten to staging (last night when I turned off afterparty in procfile and deployed), I will try to fix the data by hand and retry the deploy
```
ActiveRecord::RecordInvalid
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Contact type must exist
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:80:in `raise_validation_error'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:53:in `save!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:318:in `block in save!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:212:in `transaction'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:318:in `save!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/suppressor.rb:48:in `save!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:55:in `create!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:115:in `block in create!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:407:in `block in scoping'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:784:in `_scoping'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:407:in `scoping'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:115:in `create!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:176:in `find_or_create_by!'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/querying.rb:21:in `find_or_create_by!'
/app/lib/tasks/deployment/20201005203405_populate_case_contact_contact_type.rake:26:in `block (4 levels) in <main>'
/app/lib/tasks/deployment/20201005203405_populate_case_contact_contact_type.rake:24:in `each'
/app/lib/tasks/deployment/20201005203405_populate_case_contact_contact_type.rake:24:in `block (3 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:70:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:70:in `block in find_each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:222:in `loop'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:222:in `in_batches'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation/batches.rb:69:in `find_each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/querying.rb:21:in `find_each'
/app/lib/tasks/deployment/20201005203405_populate_case_contact_contact_type.rake:23:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.17.0/lib/bugsnag/integrations/rake.rb:20:in `execute'
/app/vendor/bundle/ruby/2.7.0/gems/after_party-1.11.2/lib/tasks/deploy_task_runner.rake:6:in `block (3 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/after_party-1.11.2/lib/tasks/deploy_task_runner.rake:6:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/after_party-1.11.2/lib/tasks/deploy_task_runner.rake:6:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.17.0/lib/bugsnag/integrations/rake.rb:20:in `execute'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/app/bin/bundle:133:in `load'
/app/bin/bundle:133:in `<main>'
Tasks: TOP => after_party:populate_case_contact_contact_type
(See full trace by running task with --trace)
W, [2020-10-14T03:14:25.937947 #34]  WARN -- [Bugsnag]: Waiting for 1 outstanding request(s)
D, [2020-10-14T03:14:25.993344 #34] DEBUG -- [Bugsnag]: Request to https://notify.bugsnag.com completed, status: 200
D, [2020-10-14T03:14:26.111458 #34] DEBUG -- [Bugsnag]: Request to https://notify.bugsnag.com completed, status: 200
D, [2020-10-14T03:14:26.136066 #34] DEBUG -- [Bugsnag]: Not notifying ActiveRecord::RecordInvalid due to ignore being signified in internal middlewares
```

**Comment by compwron** [comment]
I'm running a moderately modified version of that afterparty task. It is very n+1 xD

```
code_to_name_mapping = {
        attorney: "Attorney",
        bio_parent: "Bio Parent",
        court: "Court",
        dss_worker: "DSS Worker",
        foster_parent: "Foster Parent",
        medical_professional: "Medical Professional",
        other_family: "Other Family",
        other_support_worker: "Other Support Worker",
        school: "School",
        social_worker: "Social Worker",
        supervisor: "Supervisor",
        therapist: "Therapist",
        youth: "Youth",
    }

    funky = []
    CaseContact.find_each do |case_contact|
      casa_org = case_contact.casa_case.casa_org
      case_contact.contact_types&.each do |contact_type|
        if contact_type
          ct = ContactType.where(name: code_to_name_mapping[contact_type.to_sym]).select { |ct|
            ct.contact_type_group.casa_org == casa_org
          }.first
          if ct
            CaseContactContactType.find_or_create_by!(
                case_contact: case_contact,
                contact_type: ct
            )
          else
            funky << contact_type
          end
        else
          funky << case_contact
        end
      end
    end
    p funky```

**Comment by compwron** [comment]
```Status   Task ID         Task Name
--------------------------------------------------
  up     20200907142217  Populate prince george casa org details
  up     20200913155303  Populate missing display names
  up     20201005203140  Populate contact type groups and contact types
 down    20201005203405  Populate case contact contact type
~ $```

**Comment by compwron** [comment]
done running (took almost a minute!) this could easily be made more performant, if I push it I'll try to improve it first
ContactType.count 66
ContactTypeGroup.count 21
CaseContact.count 1767
CasaOrg.count 3
CasaAdmin.count 5
Supervisor.count 9 
Volunteer.count 113
AllCasaAdmin.count 1

**Comment by compwron** [comment]
I ran it from heroku console. It failed again. 

funky.group_by(&:to_s).map {|k, v| [k, v.count]}
`[["therapist", 411], ["dss_worker", 400], ["bio_parent", 411], ["other_support_worker", 385]]`

**Comment by compwron** [comment]
aha I see the problem. code coming soon. so many n+1, will refactor *after it works*

**Comment by compwron** [comment]
```
CaseContact.find_each do |case_contact|
      casa_org = case_contact.casa_case.casa_org
      case_contact.contact_types&.each do |contact_type|
        ct_name = code_to_name_mapping[contact_type.to_sym]
        cts_by_name = ContactType.where(name: ct_name)
        ct = cts_by_name.select { |ct| ct.contact_type_group.casa_org == casa_org }.first
        unless ct
          if cts_by_name.any?
            ctg_name = cts_by_name.first.contact_type_group.name
            org_ctg = ContactTypeGroup.where(casa_org: casa_org, name: ctg_name)
            if org_ctg
              ContactType.find_or_create_by!(contact_type_group: org_ctg, name: ct_name)
            else
              ContactTypeGroup.find_or_create_by!(casa_org: casa_org, name: ctg_name)
            end
          else
            new_ctg = ContactTypeGroup.find_or_create_by!(casa_org: casa_org, name: "#{ctg_name} Group")
            ContactType.find_or_create_by!(contact_type_group: new_ctg, name: ct_name)
          end
        end
      end
    end

    {
        ContactType: ContactType.count,
        ContactTypeGroup: ContactTypeGroup.count,
        CaseContact: CaseContact.count,
        CasaOrg: CasaOrg.count,
        CasaAdmin: CasaAdmin.count,
        Supervisor: Supervisor.count,
        Volunteer: Volunteer.count,
        AllCasaAdmin: AllCasaAdmin.count
    }
```

Ran the above, then afterparty again and it worked. I'll push this code. All previously created github issues are still valid- this needs a rewrite and a test- local developers need this to work locally! In addition to prod deploy and the redo staging deploy

```
Status   Task ID         Task Name
--------------------------------------------------
  up     20200907142217  Populate prince george casa org details
  up     20200913155303  Populate missing display names
  up     20201005203140  Populate contact type groups and contact types
  up     20201005203405  Populate case contact contact type
~ $
```

Next step is to re-try the staging deploy heroku button (it should work)

**Comment by compwron** [comment]
it worked
everything worked
See also slack https://rubyforgood.slack.com/archives/CVB0QJGVD/p1602650908260600
