### ISSUE TITLE
rake db:seed:replant errors

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1252]
https://app.bugsnag.com/ruby-for-good/casa/errors/5fa39fd859113a00184502a8?event_id=5fa39fd800622ad656880000&i=sk&m=nw
```
D, [2020-11-05T06:46:48.269065 #17] DEBUG -- :   AllCasaAdmin Create (4.2ms)  INSERT INTO "all_casa_admins" ("email", "encrypted_password", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["email", "allcasaadmin@example.com"], ["encrypted_password", "$2a$11$mzmJAyYcxaoWzrwf5axrRevy4v8XWftvNAVS.iC3nzlYdozJbZ2bm"], ["created_at", "2020-11-05 06:46:48.263557"], ["updated_at", "2020-11-05 06:46:48.263557"]]
D, [2020-11-05T06:46:48.273757 #17] DEBUG -- :    (3.8ms)  COMMIT
I, [2020-11-05T06:46:48.299838 #17]  INFO -- [Bugsnag]: Notifying https://notify.bugsnag.com of NoMethodError
rake aborted!
NoMethodError: undefined method `merge' for nil:NilClass
/app/db/seeds.rb:31:in `seed'
/app/db/seeds.rb:99:in `<main>'
/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/engine.rb:557:in `block in load_seed'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/engine.rb:675:in `with_inline_jobs'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/engine.rb:557:in `load_seed'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/railties/databases.rake:331:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.18.0/lib/bugsnag/integrations/rake.rb:20:in `execute'
Tasks: TOP => db:seed:replant => db:seed
(See full trace by running task with --trace)
D, [2020-11-05T06:46:48.402894 #17] DEBUG -- [Bugsnag]: Request to https://notify.bugsnag.com completed, status: 200
D, [2020-11-05T06:46:48.416504 #17] DEBUG -- [Bugsnag]: Not notifying NoMethodError due to ignore being signified in internal middlewares
~ $
```

**Comment by compwron** [comment]
We don't really need this, we have seed (and the readme says so). Closing.
