### ISSUE TITLE
fix bullet warning in generate reports

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1403]
Do what the stack trace says
http://localhost:3000/reports
```
user: compiledwrong
GET /case_contact_reports.csv?report%5Bstart_date%5D=2020-05-26&report%5Bend_date%5D=2020-11-25&report%5Bwant_driving_reimbursement%5D=&report%5Bwant_driving_reimbursement%5D=&report%5Bcontact_made%5D=&report%5Bcontact_made%5D=&report%5Bhas_transitioned%5D=&report%5Bhas_transitioned%5D=&commit=Download+Report
USE eager loading detected
  Volunteer => [:supervisor]
  Add to your query: .includes([:supervisor])
Call stack
  /Users/compiledwrong/repositories/casa/app/models/case_contact_report.rb:46:in `full_data'
  /Users/compiledwrong/repositories/casa/app/models/case_contact_report.rb:25:in `block (2 levels) in to_csv'
  /Users/compiledwrong/repositories/casa/app/models/case_contact_report.rb:24:in `block in to_csv'
  /Users/compiledwrong/repositories/casa/app/models/case_contact_report.rb:21:in `to_csv'
  /Users/compiledwrong/repositories/casa/app/controllers/case_contact_reports_controller.rb:12:in `block (2 levels) in index'
  /Users/compiledwrong/repositories/casa/app/controllers/case_contact_reports_controller.rb:10:in `index'
```

**Comment by notapatch** [comment]
1) I ran the seeding again to give fresh results with medium dataset.

2) I logged in as one of:
casa_admin1@example.com
supervisor1@example.com

3) Navigated to` localhost:3000/reports` and did not get an eager loading detected ...

What am I missing?

**Comment by compwron** [comment]
Closing as obsolete
