### ISSUE TITLE
Tests failing (Docker setup)

### ISSUE THREAD

**Issue by jhsu802701** [rubyforgood/casa#1461]
When I run the docker/build script, the following errors happen when running the test suite:
```bash

Failures:

  1) Rack::Attack throttle excessive requests by single IP address behaves like correctly throttles changes the request status to 429 if greater than limit
     Failure/Error: expect(last_response.status).to eq(429) if i >= limit
     
       expected: 429
            got: 200
     
       (compared using ==)
     Shared Example Group: "correctly throttles" called from ./spec/config/initializers/rack_attack_spec.rb:38
     # ./spec/config/initializers/rack_attack_spec.rb:33:in `block (5 levels) in <top (required)>'
     # ./spec/config/initializers/rack_attack_spec.rb:30:in `times'
     # ./spec/config/initializers/rack_attack_spec.rb:30:in `block (4 levels) in <top (required)>'
  2) Rack::Attack throttle excessive requests by single IP address behaves like correctly throttles changes the request status to 429 if greater than limit
     Failure/Error: expect(last_response.status).to eq(429) if i >= limit
     
       expected: 429
            got: 200
     
       (compared using ==)
     Shared Example Group: "correctly throttles" called from ./spec/config/initializers/rack_attack_spec.rb:43
     # ./spec/config/initializers/rack_attack_spec.rb:33:in `block (5 levels) in <top (required)>'
     # ./spec/config/initializers/rack_attack_spec.rb:30:in `times'
     # ./spec/config/initializers/rack_attack_spec.rb:30:in `block (4 levels) in <top (required)>'

  3) Rack::Attack throttle excessive requests for email login by variety of IP addresses behaves like correctly throttles changes the request status to 429 when greater than limit
     Failure/Error: expect(last_response.status).to eq(429) if i >= limit
     
       expected: 429
            got: 200
     
       (compared using ==)
     Shared Example Group: "correctly throttles" called from ./spec/config/initializers/rack_attack_spec.rb:73
     # ./spec/config/initializers/rack_attack_spec.rb:68:in `block (5 levels) in <top (required)>'
     # ./spec/config/initializers/rack_attack_spec.rb:64:in `times'
     # ./spec/config/initializers/rack_attack_spec.rb:64:in `block (4 levels) in <top (required)>'


  4) Rack::Attack throttle excessive requests for email login by variety of IP addresses behaves like correctly throttles changes the request status to 429 when greater than limit
     Failure/Error: expect(last_response.status).to eq(429) if i >= limit
     
       expected: 429
            got: 200
     
       (compared using ==)
     Shared Example Group: "correctly throttles" called from ./spec/config/initializers/rack_attack_spec.rb:87
     # ./spec/config/initializers/rack_attack_spec.rb:68:in `block (5 levels) in <top (required)>'
     # ./spec/config/initializers/rack_attack_spec.rb:64:in `times'
     # ./spec/config/initializers/rack_attack_spec.rb:64:in `block (4 levels) in <top (required)>'

  5) VolunteerDatatable order by contacts_made_in_past_days when descending is successful
     Failure/Error: expect(values[idx][:id]).to eq model.id.to_s
     
       expected: "559"
            got: "556"
     
       (compared using ==)
     # ./spec/datatables/volunteer_datatable_spec.rb:62:in `block (4 levels) in <top (required)>'
     # ./spec/datatables/volunteer_datatable_spec.rb:74:in `each'
     # ./spec/datatables/volunteer_datatable_spec.rb:74:in `each_with_index'
     # ./spec/datatables/volunteer_datatable_spec.rb:74:in `block (4 levels) in <top (required)>'
     # ./spec/datatables/volunteer_datatable_spec.rb:249:in `block (5 levels) in <top (required)>'

  6) VolunteerDatatable order by contacts_made_in_past_days when ascending is successful
     Failure/Error: expect(values[idx][:id]).to eq model.id.to_s
     
       expected: "554"
            got: "555"
     
       (compared using ==)
     # ./spec/datatables/volunteer_datatable_spec.rb:62:in `block (4 levels) in <top (required)>'
     # ./spec/datatables/volunteer_datatable_spec.rb:68:in `each'
     # ./spec/datatables/volunteer_datatable_spec.rb:68:in `each_with_index'
     # ./spec/datatables/volunteer_datatable_spec.rb:68:in `block (4 levels) in <top (required)>'
     # ./spec/datatables/volunteer_datatable_spec.rb:235:in `block (5 levels) in <top (required)>'

  7) VolunteerDatatable order by supervisor_name when ascending is successful
     Failure/Error: expect(values[idx][:id]).to eq model.id.to_s
     
       expected: "559"
            got: "558"
     
       (compared using ==)
     # ./spec/datatables/volunteer_datatable_spec.rb:62:in `block (4 levels) in <top (required)>'
     # ./spec/datatables/volunteer_datatable_spec.rb:68:in `each'
     # ./spec/datatables/volunteer_datatable_spec.rb:68:in `each_with_index'
     # ./spec/datatables/volunteer_datatable_spec.rb:68:in `block (4 levels) in <top (required)>'
     # ./spec/datatables/volunteer_datatable_spec.rb:122:in `block (5 levels) in <top (required)>'

  8) VolunteerDatatable order by has_transition_aged_youth_cases when descending is successful
     Failure/Error: expect(values[idx][:id]).to eq model.id.to_s
     
       expected: "559"
            got: "555"
     
       (compared using ==)
     # ./spec/datatables/volunteer_datatable_spec.rb:62:in `block (4 levels) in <top (required)>'
     # ./spec/datatables/volunteer_datatable_spec.rb:74:in `each'
     # ./spec/datatables/volunteer_datatable_spec.rb:74:in `each_with_index'
     # ./spec/datatables/volunteer_datatable_spec.rb:74:in `block (4 levels) in <top (required)>'
     # ./spec/datatables/volunteer_datatable_spec.rb:180:in `block (5 levels) in <top (required)>'

  9) VolunteerDatatable order by has_transition_aged_youth_cases when ascending is successful
     Failure/Error: expect(values[idx][:id]).to eq model.id.to_s
     
       expected: "558"
            got: "556"
     
       (compared using ==)
     # ./spec/datatables/volunteer_datatable_spec.rb:62:in `block (4 levels) in <top (required)>'
     # ./spec/datatables/volunteer_datatable_spec.rb:68:in `each'
     # ./spec/datatables/volunteer_datatable_spec.rb:68:in `each_with_index'
     # ./spec/datatables/volunteer_datatable_spec.rb:68:in `block (4 levels) in <top (required)>'
     # ./spec/datatables/volunteer_datatable_spec.rb:171:in `block (5 levels) in <top (required)>'

```

**Comment by jhsu802701** [comment]
Given that the test suite passes in the continuous integration environment, it appears that the test failures are specific to the Docker environment.

**Comment by jhsu802701** [comment]
The output of "cat /etc/os-release" in the continuous integration environment is:
```bash
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by compwron** [comment]
Hmm I thought we fixed this already. I do want to add a docker section to our CI to prevent this kind of thing. @littleforest do you have any ideas here? :)

**Comment by jhsu802701** [comment]
The Docker environment has Alpine Linux.  One option is a switch to Debian Linux or Ubuntu 18.04 in the Docker environment.  The greater the difference between the Docker environment and the CI environment, the harder it is to deal with the "but it works on my machine" problem.

**Comment by littleforest** [comment]
@jhsu802701 I'm seeing those errors too. I'll take a look later this afternoon.
