### ISSUE TITLE
fix cypress db seed flake

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1952]
https://github.com/rubyforgood/casa/pull/1942/checks?check_run_id=2349053710

```
=> Booting Puma
=> Rails 6.1.3.1 application starting in test 
=> Run `bin/rails server --help` for more startup options
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Volunteer must exist, Volunteer can't be blank, Volunteer Case assignee must be a volunteer
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/validations.rb:80:in `raise_validation_error'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/validations.rb:53:in `save!'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/transactions.rb:302:in `block in save!'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:310:in `block in within_new_transaction'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:308:in `within_new_transaction'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/transactions.rb:302:in `save!'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/suppressor.rb:48:in `save!'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/persistence.rb:55:in `create!'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:805:in `_create!'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:114:in `block in create!'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:406:in `block in scoping'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:810:in `_scoping'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:406:in `scoping'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:114:in `create!'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:175:in `find_or_create_by!'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/querying.rb:22:in `find_or_create_by!'
/home/runner/work/casa/casa/db/seeds/db_populator.rb:151:in `block in create_cases'
/home/runner/work/casa/casa/db/seeds/db_populator.rb:141:in `times'
/home/runner/work/casa/casa/db/seeds/db_populator.rb:141:in `create_cases'
/home/runner/work/casa/casa/db/seeds/db_populator.rb:48:in `create_org'
/home/runner/work/casa/casa/db/seeds.rb:32:in `seed'
/home/runner/work/casa/casa/db/seeds.rb:97:in `<main>'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/engine.rb:566:in `block in load_seed'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/engine.rb:640:in `block (2 levels) in <class:Engine>'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/engine.rb:566:in `load_seed'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:450:in `load_seed'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.1/lib/active_record/railties/databases.rake:392:in `block (2 levels) in <main>'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.20.0/lib/bugsnag/integrations/rake.rb:20:in `execute'
/home/runner/work/casa/casa/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle:23:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
Error: Process completed with exit code 1.
```

```
      casa_org_volunteers = volunteers.select { |volunteer| volunteer.casa_org_id == casa_org.id }
      CaseAssignment.find_or_create_by!(casa_case: new_casa_case, volunteer: casa_org_volunteers.sample(random: rng))
```
something in here is sometimes null

**Comment by CovenantHuman** [comment]
This was done by compwron.
