### ISSUE TITLE
Cannot run Feature Specs in Docker

### ISSUE THREAD

**Issue by ChaelCodes** [rubyforgood/casa#2022]
# Description
When I run feature specs from within Docker, they fail because of a invalid desired capability error.

1. Start Docker `docker-compose up`
1. Run a feature spec `docker-compose exec web rspec ./spec/system/case_court_reports/index_spec.rb`
1. See error

# RSpec Error
```
10.3) Failure/Error:
            def self.handshake(**opts)
              desired_capabilities = opts.delete(:desired_capabilities) { Capabilities.new }
    
              if desired_capabilities.is_a?(Symbol)
                unless Capabilities.respond_to?(desired_capabilities)
                  raise Error::WebDriverError, "invalid desired capability: #{desired_capabilities.inspect}"
                end
    
                desired_capabilities = Capabilities.__send__(desired_capabilities)
              end
  
  ArgumentError:
    wrong number of arguments (given 1, expected 0)
  # /usr/local/bundle/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:44:in `handshake'
  # /usr/local/bundle/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/driver.rb:39:in `initialize'
  # /usr/local/bundle/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:58:in `new'
  # /usr/local/bundle/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:58:in `for'
  # /usr/local/bundle/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver.rb:88:in `for'
  # /usr/local/bundle/gems/capybara-3.35.3/lib/capybara/selenium/driver.rb:83:in `browser'
  # /usr/local/bundle/gems/capybara-3.35.3/lib/capybara/selenium/driver.rb:130:in `current_url'
  # /usr/local/bundle/gems/capybara-3.35.3/lib/capybara/session.rb:229:in `current_url'
  # /usr/local/bundle/gems/capybara-screenshot-1.0.25/lib/capybara-screenshot/rspec.rb:56:in `block in after_failed_example'
  # /usr/local/bundle/gems/capybara-3.35.3/lib/capybara.rb:371:in `using_session'
  # /usr/local/bundle/gems/capybara-screenshot-1.0.25/lib/capybara-screenshot/capybara.rb:7:in `using_session'
  # /usr/local/bundle/gems/capybara-screenshot-1.0.25/lib/capybara-screenshot/rspec.rb:55:in `after_failed_example'
  # /usr/local/bundle/gems/capybara-screenshot-1.0.25/lib/capybara-screenshot/rspec.rb:99:in `block (2 levels) in <main>'
```

**Comment by compwron** [comment]
Thanks for reporting this! We definitely need to fix this.

**Comment by sosolidkk** [comment]
I can take a look into this.
