### ISSUE TITLE
Montgomery import failed

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2105]
### Impacted User Types
admin

### Environment
prod

### Current Behavior
https://app.bugsnag.com/ruby-for-good/casa/errors/60a8551961e031000762fdaf
![Screen Shot 2021-06-02 at 9 19 55 PM](https://user-images.githubusercontent.com/578159/120586416-5ae94c80-c3e8-11eb-9d35-77e70fb93fbc.png)

```
exported_rows
display_name,email,errors (please remove this column before uploading again)
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
,,Row does not contain an e-mail address.
import_error
You successfully imported 13 volunteers. Not all rows were imported.<p class='mt-4'><a href="/imports/download_failed">Click here to download failed rows.</a></p><p>Note: An additional 'error' column has been added to the file. Please note the failure reason and remove the column when resubmitting.</p>
```

```
vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/cookies.rb:678:in `commit': ActionDispatch::Cookies::CookieOverflow (ActionDispatch::Cookies::CookieOverflow)
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/cookies.rb:496:in `[]='
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/session/cookie_store.rb:110:in `set_cookie'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:403:in `commit_session'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:268:in `context'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/cookies.rb:689:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/bugsnag-6.20.0/lib/bugsnag/integrations/rack.rb:51:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
    from vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:26:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `block in tagged'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:37:in `tagged'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `tagged'
    from vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.2/lib/rails/rack/logger.rb:26:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/request_id.rb:26:in `call'
    from vendor/bundle/ruby/3.0.0/gems/skylight-5.1.0/lib/skylight/probes/action_dispatch/request_id.rb:8:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/static.rb:24:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/ssl.rb:77:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/skylight-5.1.0/lib/skylight/middleware.rb:96:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:61:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:60:in `call'
    from vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.2/lib/rails/engine.rb:539:in `call'
    from vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/configuration.rb:249:in `call'
    from vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/request.rb:77:in `block in handle_request'
    from vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:338:in `with_force_shutdown'
    from vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/request.rb:76:in `handle_request'
    from vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/server.rb:438:in `process_client'
    from vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
    ```

**Comment by compwron** [comment]
Closing as not replicable
