### ISSUE TITLE
Fix file download tests in docker

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2246]
see https://github.com/SeleniumHQ/docker-selenium/issues/548

```
Failures:

  1) case_contact_reports/index filters report by date and selected contact type
     Failure/Error: sleep 20 until downloaded?

     Timeout::Error:
       execution expired

     [Screenshot Image]: /usr/src/app/tmp/screenshots/failures_r_spec_example_groups_case_contact_reports_index_filters_report_by_date_and_selected_contact_type_33.png


     # ./spec/support/download_helpers.rb:20:in `sleep'
     # ./spec/support/download_helpers.rb:20:in `block in wait_for_download'
     # ./spec/support/download_helpers.rb:19:in `wait_for_download'
     # ./spec/system/reports/case_contact_reports_spec.rb:25:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:69:in `block (2 levels) in <top (required)>'

```

**Comment by librod89** [comment]
I spent awhile trying to figure out how to fix the failures in `case_contacts_reports_spec.rb`. But I was not successful. I'll leave my notes here in case someone else wants to pick this up.

I added the following things to the Dockerfile just in case:

```
RUN app add chromium chromium-chromedriver python3 python3-dev py3-pip
RUN pip3 install -U selenium
...
RUN chmod 777 .  ### In case the folder permissions on /tmp/downloads were causing the failure
```

I also changed the selenium driver in capybara.rb to get logging to work:

```
capabilities = Selenium::WebDriver::Remote::Capabilities.chrome({
    "goog:chromeOptions" => {
      "args" => %w[headless disable-gpu window-size=1280,900],
    },
    "goog:loggingPrefs" => { browser: 'ALL'}
  })

  Capybara::Selenium::Driver.new(app,
    browser: :remote,
    url: "http://selenium_chrome:4444/wd/hub",
    capabilities: capabilities
  )
```

You can view driver logs with `page.driver.browser.manage.logs.get(:browser)` but nothing about the download was shown here.

I was trying to edits the `capabilities` to explicitly allow downloads but I'm not sure exactly where to put these preferences:

```
'set_download_behavior' => { 'behavior' => 'allow'},
'download' => {
      'default_directory' => "/tmp/downloads",
      'prompt_for_download' => false,
      'directory_upgrade' => true
    }
```

When I add these preferences to the `capabilities` hash, I get this error: `org.openqa.selenium.SessionNotCreatedException: Unable to create session`

Also a lot of blogs suggested doing something like the following, but this always raised an error also:

```
  bridge = driver.browser.send(:bridge)
  path = '/session/:session_id/chromium/send_command'
  path[':session_id'] = bridge.session_id
  bridge.http.call(:post, path, cmd: 'Page.setDownloadBehavior',
                  params: {
                    behavior: 'allow',
                    downloadPath: "/tmp/downloads"
                  })
```
