### ISSUE TITLE
Fix Dave Typo in tests

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#2525]
```
 1) past_court_dates/new when non-mandatory fields are not filled does not create a new past_court_date
     Failure/Error: travel_to Dave.new(2021, 1, 1)

     NameError:
       uninitialized constant Dave
       Did you mean?  Date
     # ./spec/system/past_court_dates/new_spec.rb:12:in `block (2 levels) in <top (required)>'

  2) past_court_dates/new when all fields are filled is successful
     Failure/Error: travel_to Dave.new(2021, 1, 1)

     NameError:
       uninitialized constant Dave
       Did you mean?  Date

   # ./spec/system/past_court_dates/new_spec.rb:12:in `block (2 levels) in <top (required)>'

  4) view all volunteers supervisor user can show/hide columns on volunteers table
     Failure/Error: travel_to Dave.new(2021, 1, 1)

     NameError:
       uninitialized constant Dave
       Did you mean?  Date

     [Screenshot Image]: /home/runner/work/casa/casa/tmp/screenshots/failures_r_spec_example_groups_view_all_volunteers_supervisor_user_can_show_hide_columns_on_volunteers_table_781.png

     # ./spec/system/volunteers/index_spec.rb:223:in `block (3 levels) in <top (required)>'

 rspec ./spec/system/past_court_dates/new_spec.rb:51 # past_court_dates/new when non-mandatory fields are not filled does not create a new past_court_date
rspec ./spec/system/past_court_dates/new_spec.rb:22 # past_court_dates/new when all fields are filled is successful
rspec ./spec/system/volunteers/index_spec.rb:222 # view all volunteers supervisor user can show/hide columns on volunteers table

```

**Comment by RhnSharma** [comment]
I would like to take this one.
