### ISSUE TITLE
Fix or delete flaky test:  supervisors/index supervisor table filters status when only active checked filters the supervisors correctly

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#2906]
https://github.com/rubyforgood/casa/runs/4094230908?check_suite_focus=true
```
  1) supervisors/index supervisor table filters status when only active checked filters the supervisors correctly
     Failure/Error: expect(page).to have_content("Active Supervisor")
       expected to find text "Active Supervisor" in "Supervisor Name Volunteer Assignments Serving Transition Aged Youth No Attempt (14 days) Actions\nAlfonzo Hane 0 0 0 Edit"

     [Screenshot Image]: /home/runner/work/casa/casa/tmp/screenshots/failures_r_spec_example_groups_supervisors_index_supervisor_table_filters_status_when_only_active_checked_filters_the_supervisors_correctly_423.png


     # ./spec/system/supervisors/index_spec.rb:202:in `block (6 levels) in <top (required)>'
     # ./spec/system/supervisors/index_spec.rb:201:in `block (5 levels) in <top (required)>'

Finished in 7 minutes 7 seconds (files took 8.59 seconds to load)
1547 examples, 1 failure, 6 pending

Failed examples:

rspec ./spec/system/supervisors/index_spec.rb:193 # supervisors/index supervisor table filters status when only active checked filters the supervisors correctly
```

**Comment by mdchaney** [comment]
This is on my radar as well.  The code around the checkboxes in the drop-down is problematic as it has the checkboxes and labels inside of an anchor tag.  That's not valid.  I'll dig around a bit as it looks like data attributes on the <a> are being used, so fixing this might mean a little javascript rework as well.

**Comment by mdchaney** [comment]
There's another flakey test in the same file that's failing every time now.
