### ISSUE TITLE
Fix Cypress spec

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#3089]
https://github.com/rubyforgood/casa/runs/4760343587?check_suite_focus=true

```
Oops...we found an error preparing this test file:

  cypress/integration/volunteer/new_case_contact.spec.js

The error was:

Error: Webpack Compilation Error
./cypress/integration/volunteer/new_case_contact.spec.js
Module not found: Error: Can't resolve 'faker' in '/home/runner/work/casa/casa/cypress/integration/volunteer'
resolve 'faker' in '/home/runner/work/casa/casa/cypress/integration/volunteer'
  Parsed request is a module
  using description file: /home/runner/work/casa/casa/package.json (relative path: ./cypress/integration/volunteer)
    Field 'browser' doesn't contain a valid alias configuration
    Looked for and couldn't find the file at the following paths:
[/home/runner/work/casa/casa/cypress/integration/volunteer/node_modules]
[/home/runner/work/casa/casa/cypress/integration/node_modules]
[/home/runner/work/casa/casa/cypress/node_modules]
[/home/runner/work/casa/node_modules]
[/home/runner/work/node_modules]
[/home/runner/node_modules]
[/home/node_modules]
[/node_modules]
[/home/runner/work/casa/casa/node_modules/faker]
[/home/runner/work/casa/casa/node_modules/faker.js]
[/home/runner/work/casa/casa/node_modules/faker.json]
[/home/runner/work/casa/casa/node_modules/faker.jsx]
[/home/runner/work/casa/casa/node_modules/faker.mjs]
[/home/runner/work/casa/casa/node_modules/faker.coffee]
[/home/runner/work/casa/casa/node_modules/faker/index.js]
[/home/runner/work/casa/casa/node_modules/faker/index.js.js]
[/home/runner/work/casa/casa/node_modules/faker/index.js.json]
[/home/runner/work/casa/casa/node_modules/faker/index.js.jsx]
[/home/runner/work/casa/casa/node_modules/faker/index.js.mjs]
[/home/runner/work/casa/casa/node_modules/faker/index.js.coffee]
[/home/runner/work/casa/casa/node_modules/faker/index]
[/home/runner/work/casa/casa/node_modules/faker/index.json]
[/home/runner/work/casa/casa/node_modules/faker/index.jsx]
[/home/runner/work/casa/casa/node_modules/faker/index.mjs]
[/home/runner/work/casa/casa/node_modules/faker/index.coffee]
 @ ./cypress/integration/volunteer/new_case_contact.spec.js 4:14-30
 
    at handle (/home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:180:23)
    at finalCallback (/home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:298:10
    at /home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/neo-async/async.js:2818:7
    at done (/home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/graceful-fs/graceful-fs.js:61:14
    at /home/runner/.cache/Cypress/9.2.0/Cypress/resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (node:fs:188:23)

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

```

**Comment by isaacm** [comment]
Might have to rollback https://github.com/rubyforgood/casa/pull/3077

See https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected

**Comment by compwron** [comment]
Whups
Thanks

**Comment by compwron** [comment]
@isaacm can you make a PR?

**Comment by isaacm** [comment]
@compwron you might have to tell dependabot to ignore that dependency for now. 

See my comment on the PR, that got rejected by the bot.

**Comment by compwron** [comment]
This seems done. Thanks @isaacm https://github.com/rubyforgood/casa/actions/workflows/cypress.yml
