### ISSUE TITLE
Fix HTML Escape String Mismatch Supervisor Name View Test Flake

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#3886]
### Current Behavior
the test `spec/views/volunteers/index.html.erb_spec.rb` does not expect HTML escaped apostrophes 

### Expected Behavior
the test should expect HTML escaped apostrophes

### How to Replicate
In your local environment,
set the volunteer's supervisor's name to "Keith **O'Reilly"**
`bundle exec rspec spec/views/volunteers/index.html.erb_spec.rb`

### Full Error Output: 

```
 1) volunteers supervisor's dropdown when the supervisor is active shows up in the supervisor dropdown
     Failure/Error: expect(subject).to include(ERB::Util.url_encode(supervisor.display_name).gsub("%20", " ")) # don't flake on names with ' like O'Hara

       expected "<div class=\"row\">\n  <div class=\"col-sm-12 dashboard-table-header\">\n    <h1>Volunteers</h1>\n  ...      </thead>\n\n        <tbody>\n        </tbody>\n      </table>\n    </div>\n  </div>\n</div>\n" to include "Keith O%27Reilly"
       Diff:
       @@ -1,192 +1,383 @@
       -Keith O%27Reilly
       +<div class="row">
       +  <div class="col-sm-12 dashboard-table-header">
       +    <h1>Volunteers</h1>
       +    <button type="button" class="btn btn-primary mb-2 mb-md-0" data-toggle="modal" data-target="#visibleColumns">
       +      Pick displayed columns
       +    </button>
       +  </div>
       +</div>
       +<hr>
       +
       +<div class="row volunteer-filters">
       +  <div class="col-sm-12">
       +    <h4 class="pull-left mr-2">Filter by</h4>
       +    <div class="dropdown pull-left mr-2">
       +      <button class="btn btn-secondary dropdown-toggle show" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       +        Supervisor
       +      </button>
       +      <div class="dropdown-menu supervisor-options">
       +        <div class="dropdown-item form-check">
       +          <input type="checkbox" name="supervisor-option-none" id="unassigned-vol-filter" value="" class="form-check-input" data-value="" />
       +          <label class="form-check-label" for="supervisor-option-none">No supervisor assignment</label>
       +        </div>
       +          <div class="dropdown-item form-check">
       +            <input type="checkbox" name="supervisor-option-keith_oreilly" id="supervisor-option-keith_oreilly" value="Keith O&#39;Reilly" class="form-check-input" data-value="Keith O&#39;Reilly" />
       +            <label class="form-check-label" for="supervisor-option-keith_oreilly">Keith O&#39;Reilly</label>
       +          </div>
       +      </div>
       +    </div>
       +    <div class="dropdown pull-left mr-2">
       +      <button class="btn btn-secondary dropdown-toggle show" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       +        Status
       +      </button>
       +      <div class="dropdown-menu status-options" aria-labelledby="dropdownMenuButton">
       +        <div class="dropdown-item form-check">
       +          <input type="checkbox" name="status_option_active" id="status_option_active" value="true" class="form-check-input" data-value="true" checked="checked" />
       +          <label class="form-check-label" for="status_option_active">Active</label>
       +        </div>
       +        <div class="dropdown-item form-check">
       +          <input type="checkbox" name="status_option_inactive" id="status_option_inactive" value="false" class="form-check-input" data-value="false" />
       +          <label class="form-check-label" for="status_option_inactive">Inactive</label>
       +        </div>
       +      </div>
       +    </div>
       +    <div class="dropdown pull-left mr-2">
       +      <button class="btn btn-secondary dropdown-toggle show" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       +      Assigned to Transition Aged Youth
       +      </button>
       +      <div class="dropdown-menu transition-youth-options" aria-labelledby="dropdownMenuButton">
       +        <div class="dropdown-item form-check">
       +          <input type="checkbox" name="transition_youth_option_yes" id="transition_youth_option_yes" value="true" class="form-check-input" data-value="true" checked="checked" />
       +          <label class="form-check-label" for="transition_youth_option_yes">Yes</label>
       +        </div>
       +        <div class="dropdown-item form-check">
       +          <input type="checkbox" name="transition_youth_option_no" id="transition_youth_option_no" value="false" class="form-check-input" data-value="false" checked="checked" />
       +          <label class="form-check-label" for="transition_youth_option_no">No</label>
       +        </div>
       +      </div>
       +    </div>
       +  </div>
       +</div>
       +<br>
       +
       +<div class="modal fade" id="visibleColumns" tabindex="-1" role="dialog" aria-labelledby="visibleColumnsLabel" aria-hidden="true">
       +  <div class="modal-dialog" role="document">
       +    <div class="modal-content">
       +      <div class="modal-header">
       +        <h5 class="modal-title" id="visibleColumnsLabel">Pick displayed columns</h5>
       +        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
       +          <span aria-hidden="true">&times;</span>
       +        </button>
       +      </div>
       +      <div class="modal-body">
       +        <div>
       +          Select columns:
       +
       +            <div class="row">
       +              <div class="col-sm-12">
       +                <div class="form-check">
       +                  <input type="checkbox" name="pick-name" id="pick-name" value="1" class="form-check-input toggle-visibility" data-column="0" />
       +                  <label class="form-check-label" for="pick-name">Name</label>
       +                </div>
       +              </div>
       +            </div>
       +            <div class="row">
       +              <div class="col-sm-12">
       +                <div class="form-check">
       +                  <input type="checkbox" name="pick-email" id="pick-email" value="1" class="form-check-input toggle-visibility" data-column="1" />
       +                  <label class="form-check-label" for="pick-email">Email</label>
       +                </div>
       +              </div>
       +            </div>
       +            <div class="row">
       +              <div class="col-sm-12">
       +                <div class="form-check">
       +                  <input type="checkbox" name="pick-supervisor" id="pick-supervisor" value="1" class="form-check-input toggle-visibility" data-column="2" />
       +                  <label class="form-check-label" for="pick-supervisor">Supervisor</label>
       +                </div>
       +              </div>
       +            </div>
       +            <div class="row">
       +              <div class="col-sm-12">
       +                <div class="form-check">
       +                  <input type="checkbox" name="pick-status" id="pick-status" value="1" class="form-check-input toggle-visibility" data-column="3" />
       +                  <label class="form-check-label" for="pick-status">Status</label>
       +                </div>
       +              </div>
       +            </div>
       +            <div class="row">
       +              <div class="col-sm-12">
       +                <div class="form-check">
       +                  <input type="checkbox" name="pick-assigned_to_transition_aged_youth" id="pick-assigned_to_transition_aged_youth" value="1" class="form-check-input toggle-visibility" data-column="4" />
       +                  <label class="form-check-label" for="pick-assigned_to_transition_aged_youth">Assigned To Transition Aged Youth</label>
       +                </div>
       +              </div>
       +            </div>
       +            <div class="row">
       +              <div class="col-sm-12">
       +                <div class="form-check">
       +                  <input type="checkbox" name="pick-case_number" id="pick-case_number" value="1" class="form-check-input toggle-visibility" data-column="5" />
       +                  <label class="form-check-label" for="pick-case_number">Case Number</label>
       +                </div>
       +              </div>
       +            </div>
       +            <div class="row">
       +              <div class="col-sm-12">
       +                <div class="form-check">
       +                  <input type="checkbox" name="pick-last_attempted_contact" id="pick-last_attempted_contact" value="1" class="form-check-input toggle-visibility" data-column="6" />
       +                  <label class="form-check-label" for="pick-last_attempted_contact">Last Attempted Contact</label>
       +                </div>
       +              </div>
       +            </div>
       +            <div class="row">
       +              <div class="col-sm-12">
       +                <div class="form-check">
       +                  <input type="checkbox" name="pick-contact_made_in_past_60_days" id="pick-contact_made_in_past_60_days" value="1" class="form-check-input toggle-visibility" data-column="7" />
       +                  <label class="form-check-label" for="pick-contact_made_in_past_60_days">Contact Made In Past 60 Days</label>
       +                </div>
       +              </div>
       +            </div>
       +            <div class="row">
       +              <div class="col-sm-12">
       +                <div class="form-check">
       +                  <input type="checkbox" name="pick-hours_spent_in_days" id="pick-hours_spent_in_days" value="1" class="form-check-input toggle-visibility" data-column="8" />
       +                  <label class="form-check-label" for="pick-hours_spent_in_days">Hours Spent In Days</label>
       +                </div>
       +              </div>
       +            </div>
       +            <div class="row">
       +              <div class="col-sm-12">
       +                <div class="form-check">
       +                  <input type="checkbox" name="pick-actions" id="pick-actions" value="1" class="form-check-input toggle-visibility" data-column="9" />
       +                  <label class="form-check-label" for="pick-actions">Actions</label>
       +                </div>
       +              </div>
       +            </div>
       +        </div>
       +      </div>
       +      <div class="modal-footer">
       +        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
       +      </div>
       +    </div>
       +  </div>
       +</div>
       +
       +<div class="card card-container">
       +  <div class="card-body">
       +    <div class="table-responsive">
       +      <table
       +        class="table table-striped table-bordered"
       +        id="volunteers"
       +        data-source="/volunteers/datatable.json">
       +        <thead>
       +          <tr>
       +            <th>Name</th>
       +            <th>Email</th>
       +            <th>Supervisor</th>
       +            <th>Status</th>
       +            <th>Assigned To Transition Aged Youth</th>
       +            <th>Case Number(s)</th>
       +            <th>Last Attempted Contact</th>
       +            <th>Contacts Made in Past 60 Days</th>
       +            <th>Hours spent in last 30 days</th>
       +            <th>Actions</th>
       +          </tr>
       +        </thead>
       +
       +        <tbody>
       +        </tbody>
       +      </table>
       +    </div>
       +  </div>
       +</div>
     # ./spec/views/volunteers/index.html.erb_spec.rb:34:in `block (4 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 4 minutes 15.8 seconds (files took 9.27 seconds to load)
2174 examples, 1 failure, 12 pending
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by amygurski** [comment]
I'm on it!

**Comment by FireLemons** [comment]
I think I misunderstood the problem when I made the issue. The test actually does expect HTML Escaped Strings `ERB::Util.url_encode(`

**Comment by FireLemons** [comment]
Oh nevermind you got it already.
