### ISSUE TITLE
Bug: Docker Exclusive Edit Casa Case Flaky Test

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4225]
### Environment
Docker

### Current Behavior
The test in [`spec/system/casa_cases/edit_spec.rb`](https://github.com/rubyforgood/casa/blob/main/spec/system/casa_cases/edit_spec.rb) on line 179 fails sometimes in docker.  
Fix the test so that it always passes.

Example Output:  
```
  1) Edit CASA Case logged in as supervisor edits case
     Failure/Error: click_on "Update CASA Case"

     Selenium::WebDriver::Error::ElementNotInteractableError:
       element not interactable: element has zero size
         (Session info: headless chrome=94.0.4606.61)

     [Screenshot Image]: /usr/src/app/tmp/capybara/failures_r_spec_example_groups_edit_casa_case_logged_in_as_supervisor_edits_case_372.png


     # #0 0x55e4660c48f3 <unknown>
     # #1 0x55e465ba9ba8 <unknown>
     # #2 0x55e465be0dce <unknown>
     # #3 0x55e465bd4818 <unknown>
     # #4 0x55e465bfce72 <unknown>
     # #5 0x55e465bd4593 <unknown>
     # #6 0x55e465bfcf7e <unknown>
     # #7 0x55e465c0fdac <unknown>
     # #8 0x55e465bfcd63 <unknown>
     # #9 0x55e465bd3144 <unknown>
     # #10 0x55e465bd4135 <unknown>
     # #11 0x55e4660f3c3e <unknown>
     # #12 0x55e4661096b7 <unknown>
     # #13 0x55e4660f4b95 <unknown>
     # #14 0x55e46610ab05 <unknown>
     # #15 0x55e4660e92ab <unknown>
     # #16 0x55e466125248 <unknown>
     # #17 0x55e4661253c8 <unknown>
     # #18 0x55e46614033d <unknown>
     # #19 0x7f16fb003609 start_thread
     # /usr/local/bundle/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
     # /usr/local/bundle/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/remote/response.rb:35:in `initialize'
     # /usr/local/bundle/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
     # /usr/local/bundle/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
     # /usr/local/bundle/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/remote/http/default.rb:103:in `request'
     # /usr/local/bundle/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
     # /usr/local/bundle/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/remote/bridge.rb:625:in `execute'
     # /usr/local/bundle/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/remote/bridge.rb:396:in `click_element'
     # /usr/local/bundle/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/common/element.rb:77:in `click'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/selenium/node.rb:110:in `click'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/selenium/extensions/file_input_click_emulation.rb:6:in `click'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/selenium/nodes/chrome_node.rb:40:in `click'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/node/element.rb:172:in `block in click'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/node/element.rb:608:in `block in perform_click_action'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/node/base.rb:83:in `synchronize'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/node/element.rb:608:in `perform_click_action'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/node/element.rb:171:in `click'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/node/actions.rb:26:in `click_link_or_button'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/session.rb:771:in `click_on'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/dsl.rb:52:in `call'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/dsl.rb:52:in `click_on'
     # ./spec/system/casa_cases/edit_spec.rb:196:in `block (4 levels) in <top (required)>'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/session.rb:363:in `within'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/dsl.rb:52:in `call'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/dsl.rb:52:in `within_element'
     # /usr/local/bundle/gems/capybara-3.37.1/lib/capybara/rspec/matcher_proxies.rb:15:in `within'
     # ./spec/system/casa_cases/edit_spec.rb:195:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 4 minutes 11.2 seconds (files took 8.94 seconds to load)
2270 examples, 1 failure, 10 pending

Failed examples:

rspec ./spec/system/casa_cases/edit_spec.rb:179 # Edit CASA Case logged in as supervisor edits case
```

### How to Replicate
Run the test many times?

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
Still needs fixing

**Comment by FireLemons** [comment]
Hasn't been seen in a while
