### ISSUE TITLE
Bug: Learning Hour Report Timeout Flake

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4245]
### Environment
All

### Current Behavior
Sometimes the test in `spec/models/learning_hours_report_spec.rb` on line 20 times out. Example Output:

```
 1) LearningHoursReport#to_csv when there are learning hours includes all learning hours
     Failure/Error: sleep 0.025 while not_include_fields?(model, result, fields)

     Timeout::Error:
       execution expired
     # ./spec/support/csv_exporter_helper.rb:6:in `sleep'
     # ./spec/support/csv_exporter_helper.rb:6:in `block in wait_for_csv_parse'
     # /usr/local/bundle/gems/timeout-0.3.0/lib/timeout.rb:179:in `block in timeout'
     # /usr/local/bundle/gems/timeout-0.3.0/lib/timeout.rb:36:in `block in catch'
     # /usr/local/bundle/gems/timeout-0.3.0/lib/timeout.rb:36:in `catch'
     # /usr/local/bundle/gems/timeout-0.3.0/lib/timeout.rb:36:in `catch'
     # /usr/local/bundle/gems/timeout-0.3.0/lib/timeout.rb:188:in `timeout'
     # ./spec/support/csv_exporter_helper.rb:5:in `wait_for_csv_parse'
     # ./spec/models/learning_hours_report_spec.rb:23:in `block (5 levels) in <top (required)>'
     # ./spec/models/learning_hours_report_spec.rb:22:in `each'
     # ./spec/models/learning_hours_report_spec.rb:22:in `each_with_index'
     # ./spec/models/learning_hours_report_spec.rb:22:in `block (4 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

### Expected Behavior
The test passes every time when the code is working.

### How to Replicate
I guess the only thing to do is try running the test a lot locally.

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

**Comment by FireLemons** [comment]
Oh no you don't bot we still need this

**Comment by cliiint** [comment]
Grabbing this one, hope to be able to reproduce!

**Comment by FireLemons** [comment]
cliiint tried this and it was unreproducable locally
