### ISSUE TITLE
Bug: Factorybot Lint Flake

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4749]
See `lib/tasks/lint_factory_bot.rake`

### Environment
ex: github actions aka CI

### Current Behavior
Example Error Output

```
FactoryBot::InvalidFactoryError: The following factories are invalid:

* user_language - Validation failed: Name has already been taken (ActiveRecord::RecordInvalid)
/home/runner/work/casa/casa/vendor/bundle/ruby/3.1.0/gems/factory_bot-6.2.1/lib/factory_bot/linter.rb:13:in `lint!'
/home/runner/work/casa/casa/vendor/bundle/ruby/3.1.0/gems/factory_bot-6.2.1/lib/factory_bot.rb:70:in `lint'
/home/runner/work/casa/casa/lib/tasks/lint_factory_bot.rake:7:in `block (3 levels) in <top (required)>'
/home/runner/work/casa/casa/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/home/runner/work/casa/casa/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/runner/work/casa/casa/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/runner/work/casa/casa/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/runner/work/casa/casa/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/runner/work/casa/casa/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/home/runner/work/casa/casa/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/home/runner/work/casa/casa/lib/tasks/lint_factory_bot.rake:6:in `block (2 levels) in <top (required)>'
/home/runner/work/casa/casa/vendor/bundle/ruby/3.1.0/gems/bugsnag-6.25.2/lib/bugsnag/integrations/rake.rb:20:in `execute'
/home/runner/work/casa/casa/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.1.2/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.1.2/x64/bin/bundle:25:in `<main>'
```

### Expected Behavior
Linting catches only invalid factories

### How to Replicate
run `bundle exec rake factory_bot:lint RAILS_ENV='test'` many times. It will fail sometimes.

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by aboongm** [comment]
I want to work on this.
