### ISSUE TITLE
Bug: Placement Test Date Format Mismatch Flake

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#4794]
### Current Behavior
test expects `May 02, 2023` on a page but instead the page contains `May 2, 2023`  
Example Output:
```
 1) casa_cases/show when there is a placement renders casa case with placements
     Failure/Error: expect(rendered).to match(placement_started_at)

       expected "<div class=\"row\">\n  <div id=\"thank-you-modal-wrapper\">\n  <div class=\"modal fade\" id=\"thank_...tion.href)) {\n      window.localStorage.removeItem('casa-contact-form')\n    }\n  });\n</script>\n" to match "May 02, 2023"
       Diff:
       @@ -1,104 +1,207 @@
       -May 02, 2023
       +<div class="row">
       +  <div id="thank-you-modal-wrapper">
       +  <div class="modal fade" id="thank_you" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
       +    <div class="modal-dialog modal-dialog-centered">
       +      <div class="modal-content">
       +        <div class="modal-header">
       +          Case contact was successfully created. Thanks for being a great volunteer!
       +        </div>
       +          <div id="prompt-update-user" class="modal-body">
       +            Please enter any past or future court dates if you know them so that court reports can be generated with the correct case contacts.
       +          </div>
       +        <div class="modal-footer">
       +          <button type="button" class="main-btn secondary-btn btn-sm" data-bs-dismiss="modal">Close</button>
       +        </div>
       +      </div>
       +    </div>
       +  </div>
       +</div>
       +
       +  <div class="col-sm-12 form-header my-4">
       +    <h1 class="pull-left">🦋CASA Case Details</h1>
       +      <a class="main-btn primary-btn btn-sm btn-hover pull-left casa-case-button" href="/case_contacts/new?case_contact%5Bcasa_case_id%5D=1775">
       +        <i class="lni lni-plus mr-10"></i>
       +        New Case Contact
       +</a>      <a class="main-btn primary-btn btn-sm btn-hover pull-left casa-case-button pull-left casa-case-button" href="/casa_cases/111/edit">
       +        <i class="lni lni-pencil mr-10"></i>
       +        Edit Case Details
       +</a>      <a class="main-btn primary-btn btn-sm pull-left casa-case-button" href="/casa_cases/111/emancipation">
       +        Emancipation
       +        <span class="badge badge-light">
       +          0 / 0
       +        </span>
       +</a>    <form class="d-inline" action="/case_court_reports/generate" accept-charset="UTF-8" data-remote="true" method="post">
       +      <input value="111" autocomplete="off" type="hidden" name="case_number" id="case_number" />
       +      <button name="button" type="submit" data-button-name="Generate Report" id="btnGenerateReport" class="main-btn success-btn btn-hover btn-sm pull-right mb-2">Generate Report</button>
       +      <i id="spinner" class='fas fa-spin d-none pull-right'>⏳</i>
       +</form>  </div>
       +</div>
       +<div class="card card-container">
       +  <div class="card-body">
       +    <p>
       +      <h6><strong>Case number:</strong> 111</h6>
       +    </p>
       +    <p>
       +      <h6><strong>Transition Aged Youth:</strong> Yes 🦋</h6>
       +    </p>
       +    <div>
       +      <h6>
       +        <strong>
       +          Youth's Date in Care:
       +        </strong>
       +        
       +        
       +      </h6>
       +    </div>
       +    <p>
       +      <h6>
       +        <strong>Next Court Date:</strong>
       +        
       +        <!-- Button code -->
       +
       +      </h6>
       +    </p>
       +    <p>
       +      <h6>
       +        <strong>Court Report Status:</strong>
       +        Not submitted</h6>
       +    </p>
       +    <label>Court dates:</label>
       +  No Court Dates
       +<ul>
       +  <div class="add-container past-court-dates my-3">
       +    <a class="main-btn btn-sm primary-btn btn-hover ml-3" href="/casa_cases/111/court_dates/new">
       +      <i class="lni lni-plus"></i>
       +      Add a court date
       +</a>  </div>
       +</ul>
       +
       +    <label>Placements:</label>
       +  <ul>
       +      <p>
       +        <a href="/casa_cases/111/placements/6">Started At:  May 2, 2023 - Placement Type: Placement Type 8</a>
       +      </p>
       +  </ul>
       +
       +    <div>
       +      <h6><strong>Assigned Volunteers:</strong></h6>
       +      <div class="container">
       +      </div>
       +      <br>
       +      <div id="case_contacts_list">
       +          
       +      </div>
       +    </div>
       +  </div>
       +</div>
       +
       +<script>
       +  document.addEventListener("DOMContentLoaded", () => {
       +    if (/\/casa_cases\/.*\?.*success=true/.test(window.location.href)) {
       +      window.localStorage.removeItem('casa-contact-form')
       +  

  }
       +  });
       +</script>
     # ./spec/views/casa_cases/show.html.erb_spec.rb:59:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

### Expected Behavior
Test passes for days under 10 when placements are working correctly

See `spec/views/casa_cases/show.html.erb_spec.rb`

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by DariBerrie** [comment]
@FireLemons I'd be interested in taking this on if it's still available.
