### ISSUE TITLE
Bug: Flaky Test Did not Recieve Confirmation Text After Re-Sending an invitation to an Admin

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5123]
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself
Fix the test so it runs consistently.

### CI Workflow
rspec in docker

### Sample Error Output:
```
  2) casa_admins/edit can resend invitation to a another admin
     Failure/Error: expect(page).to have_content("Invitation sent")
       expected to find text "Invitation sent" in "Inbox\nSupervisors\nVolunteers\nOther Duties\nCases\nAdmins\nGroup Actions\nMenu\nUser 1735\nEdit Casa Admin\nEmail\nDisplay name\nPhone number\nEmail Reimbursement Requests\nCASA organization CASA Org 1316\nAdded to system August 16, 2023\nInvitation email sent never\nLast logged in never\nInvitation accepted never\nPassword reset last sent never\nWill receive reimbursement request emails No\nAdmin is\nACTIVE\nDeactivate Resend Invitation Change to Supervisor\nSubmit\n© CASA / Volunteer Tracking\nBuilt with by Ruby For Good\nReport a site issue\nSMS Terms & Conditions"

     # ./spec/system/casa_admins/edit_spec.rb:105:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by compwron** [comment]
I am closing this as old. We may bring it back in a different form.
