### ISSUE TITLE
Bug: Flaky Test Unable to Find Warning Modal Before Attempting to Deactivate a Supervisor

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5127]
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself
Fix the test so it runs consistently.

### CI Workflow
rspec in docker

### Sample Error Output:
```
   2) supervisors/edit logged in as an admin can deactivate a supervisor
     Failure/Error:
       dismiss_confirm do
         find("a[href='#{deactivate_supervisor_path(supervisor)}']").click
       end

     Capybara::ModalNotFound:
       Unable to find modal dialog

     ...
     # ./spec/system/supervisors/edit_spec.rb:80:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Selenium::WebDriver::Error::TimeoutError:
     #   timed out after 2 seconds (no such alert
     #     (Session info: headless chrome=94.0.4606.61))
     #   /usr/local/bundle/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/wait.rb:73:in `until'

Failed examples:

rspec ./spec/system/supervisors/edit_spec.rb:74 # supervisors/edit logged in as an admin can deactivate a supervisor
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by andreLumor** [comment]
Hi! Can I work on this issue?

**Comment by compwron** [comment]
I am closing this as old. We may bring it back in a different form.
