### ISSUE TITLE
Bug: Flaky Test Did not Receive Confirmation Text After Changing Admin to Supervisor

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5130]
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself
Fix the test so it runs consistently.

### CI Workflow
rspec in docker

### Sample Error Output:
```
  1) casa_admins/edit can convert the admin to a supervisor
     Failure/Error: expect(page).to have_text("Admin was changed to Supervisor.")
       expected to find text "Admin was changed to Supervisor." in "Inbox\nSupervisors\nVolunteers\nOther Duties\nCases\nAdmins\nGroup Actions\nMenu\nUser 1960\nEdit Casa Admin\nEmail\nDisplay name\nPhone number\nEmail Reimbursement Requests\nCASA organization CASA Org 1618\nAdded to system August 15, 2023\nInvitation email sent never\nLast logged in never\nInvitation accepted never\nPassword reset last sent never\nWill receive reimbursement request emails No\nAdmin is\nACTIVE\nDeactivate Resend Invitation Change to Supervisor\nSubmit\n© CASA / Volunteer Tracking\nBuilt with by Ruby For Good\nReport a site issue\nSMS Terms & Conditions"

     [Screenshot Image]: /usr/src/app/tmp/capybara/failures_r_spec_example_groups_casa_admins_edit_can_convert_the_admin_to_a_supervisor_465.png


     # ./spec/system/casa_admins/edit_spec.rb:114:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

**Comment by tonyaraujop** [comment]
Hey there, can I work on this one?

**Comment by FireLemons** [comment]
:medal_sports:

**Comment by FireLemons** [comment]
Not fixed

**Comment by compwron** [comment]
I am closing this as old. We may bring it back in a different form.
